### ISSUE TITLE
403 Access Forbidden by CSRFProtector!

### ISSUE THREAD

**Issue by maui1911** [opendocman/opendocman#306]
I get this message after trying to log in.

Using docker install.

this is my docker compose.yaml

I use traefik v2 as reverse proxy

```
version: '3'
services:
  db:
    container_name: hostname_mysql
    image: mariadb:10.4
    volumes:
      - ./odm-db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=opendocman
      - MYSQL_USER=opendocman
      - MYSQL_PASSWORD=opendocman
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - 3306:3306
    networks:
      - local

  app:
    container_name: hostname_opendocman
    build: .
    depends_on:
      - db
    ports:
      - 8180:80
  #    - 443:443
  #    - 9000:9000
    hostname: doc.hostname.nl
    environment:
      - APP_DB_HOST=db
      - DB_PORT=3306
      - APP_DB_NAME=opendocman
      - APP_DB_USER=opendocman
      - APP_DB_PASS=opendocman
      - ODM_DATA_DIR=/var/www/document_repository
      - IS_DOCKER=true
    command: ["./wait-for-mysql.sh", "db", "/start.sh"]
    volumes:
      - ./odm-files-data:/var/www/document_repository
      - ./odm-docker-configs:/var/www/html/docker-configs
    labels:
      traefik.enable: "true"
      traefik.docker.network: web
      traefik.http.routers.app.rule: Host(`doc.hostname.nl`)   
      traefik.http.routers.app.entrypoints: websecure
      traefik.http.routers.app.tls: true
      traefik.http.routers.app.tls.certresolver: myresolver
    networks:
      - web
      - local

networks:
  web:
    external: true
  local:
    external: false

```
